### ISSUE TITLE
What's with Pinterest?

### ISSUE THREAD

**Issue by bkjproductions** [nielslange/smntcs-adobe-typekit-fonts#1]
There seems to be some sort of instructions relevant to Pinterest here? I thought this was a plugin for Typekit, what does Pinterest have to do with it? :)

**Comment by nielslange** [comment]
> There seems to be some sort of instructions relevant to Pinterest here? I thought this was a plugin for Typekit, what does Pinterest have to do with it? :)

@bkjproductions I've accidentally used the wrong slug. This plugin indeed helps to add Adobe Typekit Fonts to your site and does not include Pinterest functionality. Thanks for pointing this out and sorry for the confusion. Also, sorry for my late reply. I've just seen your comment now.
